---
  env:
    browser: true
    node: true

  parserOptions:
    ecmaVersion: 8

  extends: "eslint:recommended"
  rules:
    eqeqeq:
      - "error"
      - "always"
      - null: "ignore"
    # in this case the console is needed as default behavior
    # no-console: "warn"
    no-console: "off"

    # styles
    indent:
      - "error"
      - 2
    semi:
      - "error"
    semi-spacing:
      - "error"
    switch-colon-spacing: "error"
    spaced-comment: "error"
    quotes:
      - "error"
      - "single"
      - allowTemplateLiterals: true
    quote-props:
      - "error"
      - "consistent-as-needed"
    brace-style:
      - "error"
      - "1tbs"
    comma-style:
      - "error"
      - "last"
    comma-spacing:
      - "error"
      - before: false
        after: true
    func-style:
      - "error"
      - "declaration"
      - allowArrowFunctions: true
