---
styleguide: plataformatec/linters
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- docs
- test
- coverage
- node_modules
- .nyc_output
- **/*.md
