sudo: false

dist: trusty

language: node_js

cache:
  directories:
    - "node_modules"

matrix:
  fast_finish: true
  include:
    - node_js: '8'
    - node_js: '7'
    - node_js: '6'

install:
  - npm install

script:
  - npm test
  - npm run lint

after_success:
  - npm run coverage
  - npm run coveralls
